# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'scedule_botton.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 461)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(0, 0, 651, 491))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 0, item)
        self.b0_0 = QtWidgets.QPushButton(self.centralwidget)
        self.b0_0.setGeometry(QtCore.QRect(50, 20, 101, 31))
        self.b0_0.setObjectName("b0_0")
        self.b4_4 = QtWidgets.QPushButton(self.centralwidget)
        self.b4_4.setGeometry(QtCore.QRect(450, 140, 101, 31))
        self.b4_4.setObjectName("b4_4")
        self.b3_ = QtWidgets.QPushButton(self.centralwidget)
        self.b3_.setGeometry(QtCore.QRect(450, 110, 101, 31))
        self.b3_.setObjectName("b3_")
        self.b2_4 = QtWidgets.QPushButton(self.centralwidget)
        self.b2_4.setGeometry(QtCore.QRect(450, 80, 101, 31))
        self.b2_4.setObjectName("b2_4")
        self.b1_4 = QtWidgets.QPushButton(self.centralwidget)
        self.b1_4.setGeometry(QtCore.QRect(450, 50, 101, 31))
        self.b1_4.setObjectName("b1_4")
        self.b5_3 = QtWidgets.QPushButton(self.centralwidget)
        self.b5_3.setGeometry(QtCore.QRect(350, 170, 101, 31))
        self.b5_3.setObjectName("b5_3")
        self.b4_3 = QtWidgets.QPushButton(self.centralwidget)
        self.b4_3.setGeometry(QtCore.QRect(350, 140, 101, 31))
        self.b4_3.setObjectName("b4_3")
        self.b3_3 = QtWidgets.QPushButton(self.centralwidget)
        self.b3_3.setGeometry(QtCore.QRect(350, 110, 101, 31))
        self.b3_3.setObjectName("b3_3")
        self.b2_3 = QtWidgets.QPushButton(self.centralwidget)
        self.b2_3.setGeometry(QtCore.QRect(350, 80, 101, 31))
        self.b2_3.setObjectName("b2_3")
        self.b1_3 = QtWidgets.QPushButton(self.centralwidget)
        self.b1_3.setGeometry(QtCore.QRect(350, 50, 101, 31))
        self.b1_3.setObjectName("b1_3")
        self.b5_2 = QtWidgets.QPushButton(self.centralwidget)
        self.b5_2.setGeometry(QtCore.QRect(250, 170, 101, 31))
        self.b5_2.setObjectName("b5_2")
        self.b4_2 = QtWidgets.QPushButton(self.centralwidget)
        self.b4_2.setGeometry(QtCore.QRect(250, 140, 101, 31))
        self.b4_2.setObjectName("b4_2")
        self.b3_2 = QtWidgets.QPushButton(self.centralwidget)
        self.b3_2.setGeometry(QtCore.QRect(250, 110, 101, 31))
        self.b3_2.setObjectName("b3_2")
        self.b2_2 = QtWidgets.QPushButton(self.centralwidget)
        self.b2_2.setGeometry(QtCore.QRect(250, 80, 101, 31))
        self.b2_2.setObjectName("b2_2")
        self.b1_2 = QtWidgets.QPushButton(self.centralwidget)
        self.b1_2.setGeometry(QtCore.QRect(250, 50, 101, 31))
        self.b1_2.setObjectName("b1_2")
        self.b5_1 = QtWidgets.QPushButton(self.centralwidget)
        self.b5_1.setGeometry(QtCore.QRect(150, 170, 101, 31))
        self.b5_1.setObjectName("b5_1")
        self.b4_1 = QtWidgets.QPushButton(self.centralwidget)
        self.b4_1.setGeometry(QtCore.QRect(150, 140, 101, 31))
        self.b4_1.setObjectName("b4_1")
        self.b3_1 = QtWidgets.QPushButton(self.centralwidget)
        self.b3_1.setGeometry(QtCore.QRect(150, 110, 101, 31))
        self.b3_1.setObjectName("b3_1")
        self.b2_1 = QtWidgets.QPushButton(self.centralwidget)
        self.b2_1.setGeometry(QtCore.QRect(150, 80, 101, 31))
        self.b2_1.setObjectName("b2_1")
        self.b5_0 = QtWidgets.QPushButton(self.centralwidget)
        self.b5_0.setGeometry(QtCore.QRect(50, 170, 101, 31))
        self.b5_0.setObjectName("b5_0")
        self.b4_0 = QtWidgets.QPushButton(self.centralwidget)
        self.b4_0.setGeometry(QtCore.QRect(50, 140, 101, 31))
        self.b4_0.setObjectName("b4_0")
        self.b3_0 = QtWidgets.QPushButton(self.centralwidget)
        self.b3_0.setGeometry(QtCore.QRect(50, 110, 101, 31))
        self.b3_0.setObjectName("b3_0")
        self.b2_0 = QtWidgets.QPushButton(self.centralwidget)
        self.b2_0.setGeometry(QtCore.QRect(50, 80, 101, 31))
        self.b2_0.setObjectName("b2_0")
        self.b1_0 = QtWidgets.QPushButton(self.centralwidget)
        self.b1_0.setGeometry(QtCore.QRect(50, 50, 101, 31))
        self.b1_0.setObjectName("b1_0")
        self.b1_1 = QtWidgets.QPushButton(self.centralwidget)
        self.b1_1.setGeometry(QtCore.QRect(150, 50, 101, 31))
        self.b1_1.setObjectName("b1_1")
        self.b0_1 = QtWidgets.QPushButton(self.centralwidget)
        self.b0_1.setGeometry(QtCore.QRect(150, 20, 101, 31))
        self.b0_1.setObjectName("b0_1")
        self.b0_2 = QtWidgets.QPushButton(self.centralwidget)
        self.b0_2.setGeometry(QtCore.QRect(250, 20, 101, 31))
        self.b0_2.setObjectName("b0_2")
        self.b0_3 = QtWidgets.QPushButton(self.centralwidget)
        self.b0_3.setGeometry(QtCore.QRect(350, 20, 101, 31))
        self.b0_3.setObjectName("b0_3")
        self.b0_4 = QtWidgets.QPushButton(self.centralwidget)
        self.b0_4.setGeometry(QtCore.QRect(450, 20, 101, 31))
        self.b0_4.setObjectName("b0_4")
        self.b2_5 = QtWidgets.QPushButton(self.centralwidget)
        self.b2_5.setGeometry(QtCore.QRect(550, 80, 101, 31))
        self.b2_5.setObjectName("b2_5")
        self.b5_4 = QtWidgets.QPushButton(self.centralwidget)
        self.b5_4.setGeometry(QtCore.QRect(450, 170, 101, 31))
        self.b5_4.setObjectName("b5_4")
        self.b5_5 = QtWidgets.QPushButton(self.centralwidget)
        self.b5_5.setGeometry(QtCore.QRect(550, 170, 101, 31))
        self.b5_5.setObjectName("b5_5")
        self.b4_5 = QtWidgets.QPushButton(self.centralwidget)
        self.b4_5.setGeometry(QtCore.QRect(550, 140, 101, 31))
        self.b4_5.setObjectName("b4_5")
        self.b3_5 = QtWidgets.QPushButton(self.centralwidget)
        self.b3_5.setGeometry(QtCore.QRect(550, 110, 101, 31))
        self.b3_5.setObjectName("b3_5")
        self.b0_5 = QtWidgets.QPushButton(self.centralwidget)
        self.b0_5.setGeometry(QtCore.QRect(550, 20, 101, 31))
        self.b0_5.setObjectName("b0_5")
        self.b1_5 = QtWidgets.QPushButton(self.centralwidget)
        self.b1_5.setGeometry(QtCore.QRect(550, 50, 101, 31))
        self.b1_5.setObjectName("b1_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menufile = QtWidgets.QMenu(self.menubar)
        self.menufile.setObjectName("menufile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionnew = QtWidgets.QAction(MainWindow)
        self.actionnew.setObjectName("actionnew")
        self.actionsave = QtWidgets.QAction(MainWindow)
        self.actionsave.setObjectName("actionsave")
        self.actionsave_as = QtWidgets.QAction(MainWindow)
        self.actionsave_as.setObjectName("actionsave_as")
        self.menufile.addAction(self.actionnew)
        self.menufile.addAction(self.actionsave)
        self.menufile.addAction(self.actionsave_as)
        self.menubar.addAction(self.menufile.menuAction())
        self.class1 = 8
        self.dict_7 = {101: [['', '', '', '', '', ''], ['', '', '', '', '', ''], ['', '', '', '', '', ''], ['', '', '', '', '', ''], ['', '', '', '', '', ''], ['', '', '', '', '', '']], 102: [['', '', '', '', '', ''], ['', '', '', '', '', ''], ['', '', '', '', '', ''], ['', '', '', '', '', ''], ['', '', '', '', '', ''], ['', '', '', '', '', '']], 103: [['', '', '', '', '', ''], ['', '', '', '', '', ''], ['', '', '', '', '', ''], ['', '', '', '', '', ''], ['', '', '', '', '', ''], ['', '', '', '', '', '']], 104: [['', '', '', '', '', ''], ['', '', '', '', '', ''], ['', '', '', '', '', ''], ['', '', '', '', '', ''], ['', '', '', '', '', ''], ['', '', '', '', '', '']]}
        self.dict_8 = {201: [['1', '1, 2', '', '', '', ''], ['2', '1', '', '', '', ''], ['3', '', '', '', '', ''], ['4', '', '', '', '', ''], ['5', '', '', '', '', ''], ['6', '', '', '', '', '']], 202: [['', '', '', '', '', ''], ['', '', '', '', '', ''], ['', '', '', '', '', ''], ['', '', '', '', '', ''], ['', '', '', '', '', ''], ['', '', '', '', '', '']]}
        self.class_room = dict(self.dict_8)
        self.dict_9 = {301: [['', '', '', '', '', ''], ['', '', '', '', '', ''], ['', '', '', '', '', ''], ['', '', '', '', '', ''], ['', '', '', '', '', ''], ['', '', '', '', '', '']], 302: [['', '', '', '', '', ''], ['', '', '', '', '', ''], ['', '', '', '', '', ''], ['', '', '', '', '', ''], ['', '', '', '', '', ''], ['', '', '', '', '', '']], 303: [['', '', '', '', '', ''], ['', '', '', '', '', ''], ['', '', '', '', '', ''], ['', '', '', '', '', ''], ['', '', '', '', '', ''], ['', '', '', '', '', '']]}
        self.num = 201

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "شنبه"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "یک‌شنبه"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "دو‌شنبه"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "سه‌شنبه"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "چهار‌شنبه"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "پنج‌شنبه"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "6"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("MainWindow", "ریاضی"))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("MainWindow", "زبان"))
        item = self.tableWidget.item(2, 0)
        item.setText(_translate("MainWindow", "آزمایشگاه"))
        item = self.tableWidget.item(3, 0)
        item.setText(_translate("MainWindow", "ادبیات"))
        item = self.tableWidget.item(3, 1)
        item.setText(_translate("MainWindow", "ادبیات"))
        item = self.tableWidget.item(3, 2)
        item.setText(_translate("MainWindow", "ورزش"))
        item = self.tableWidget.item(3, 3)
        item.setText(_translate("MainWindow", "ورزش"))
        item = self.tableWidget.item(3, 4)
        item.setText(_translate("MainWindow", "تاریخ"))
        item = self.tableWidget.item(4, 0)
        item.setText(_translate("MainWindow", "زیست"))
        item = self.tableWidget.item(5, 0)
        item.setText(_translate("MainWindow", "پویش"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.b0_0.setText(_translate("MainWindow", self.class_room[self.num][0][0]))
        self.b4_4.setText(_translate("MainWindow", self.class_room[self.num][4][4]))
        self.b3_.setText(_translate("MainWindow", self.class_room[self.num][3][4]))
        self.b2_4.setText(_translate("MainWindow", self.class_room[self.num][2][4]))
        self.b1_4.setText(_translate("MainWindow", self.class_room[self.num][1][4]))
        self.b5_3.setText(_translate("MainWindow", self.class_room[self.num][5][3]))
        self.b4_3.setText(_translate("MainWindow", self.class_room[self.num][4][3]))
        self.b3_3.setText(_translate("MainWindow", self.class_room[self.num][3][3]))
        self.b2_3.setText(_translate("MainWindow", self.class_room[self.num][2][3]))
        self.b1_3.setText(_translate("MainWindow", self.class_room[self.num][1][3]))
        self.b5_2.setText(_translate("MainWindow", self.class_room[self.num][5][2]))
        self.b4_2.setText(_translate("MainWindow", self.class_room[self.num][4][2]))
        self.b3_2.setText(_translate("MainWindow", self.class_room[self.num][3][2]))
        self.b2_2.setText(_translate("MainWindow", self.class_room[self.num][2][2]))
        self.b1_2.setText(_translate("MainWindow", self.class_room[self.num][1][2]))
        self.b5_1.setText(_translate("MainWindow", self.class_room[self.num][5][1]))
        self.b4_1.setText(_translate("MainWindow", self.class_room[self.num][4][1]))
        self.b3_1.setText(_translate("MainWindow", self.class_room[self.num][3][1]))
        self.b2_1.setText(_translate("MainWindow", self.class_room[self.num][2][1]))
        self.b5_0.setText(_translate("MainWindow", self.class_room[self.num][5][0]))
        self.b4_0.setText(_translate("MainWindow", self.class_room[self.num][4][0]))
        self.b3_0.setText(_translate("MainWindow", self.class_room[self.num][3][0]))
        self.b2_0.setText(_translate("MainWindow", self.class_room[self.num][2][0]))
        self.b1_0.setText(_translate("MainWindow", self.class_room[self.num][1][0]))
        self.b1_1.setText(_translate("MainWindow", self.class_room[self.num][1][1]))
        self.b0_1.setText(_translate("MainWindow", self.class_room[self.num][0][1]))
        self.b0_2.setText(_translate("MainWindow", self.class_room[self.num][0][2]))
        self.b0_3.setText(_translate("MainWindow", self.class_room[self.num][0][3]))
        self.b0_4.setText(_translate("MainWindow", self.class_room[self.num][0][4]))
        self.b2_5.setText(_translate("MainWindow", self.class_room[self.num][2][5]))
        self.b5_4.setText(_translate("MainWindow", self.class_room[self.num][5][4]))
        self.b5_5.setText(_translate("MainWindow", self.class_room[self.num][5][5]))
        self.b4_5.setText(_translate("MainWindow", self.class_room[self.num][5][4]))
        self.b3_5.setText(_translate("MainWindow", self.class_room[self.num][3][5]))
        self.b0_5.setText(_translate("MainWindow", self.class_room[self.num][0][5]))
        self.b1_5.setText(_translate("MainWindow", self.class_room[self.num][1][5]))
        self.menufile.setTitle(_translate("MainWindow", "file"))
        self.actionnew.setText(_translate("MainWindow", "new"))
        self.actionnew.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionsave.setText(_translate("MainWindow", "save"))
        self.actionsave_as.setText(_translate("MainWindow", "save as"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
